Document: cbacklight
Title: Debian cbacklight Manual
Author: <insert document author here>
Abstract: This manual describes what cbacklight is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/cbacklight/cbacklight.sgml.gz

Format: postscript
Files: /usr/share/doc/cbacklight/cbacklight.ps.gz

Format: text
Files: /usr/share/doc/cbacklight/cbacklight.text.gz

Format: HTML
Index: /usr/share/doc/cbacklight/html/index.html
Files: /usr/share/doc/cbacklight/html/*.html
